
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

source:              source

gems:
  - jekyll-sitemap

# Setup
title:               PCDM
tagline:             Portland Common Data Model
description:         'PCDM Community Resources'
url:                 http://pcdm.org
baseurl:             ''

# About/contact
author:
  name:              Nick Ruest
  url:               https://twitter.com/pcdmorg
  email:             ruestn@yorku.ca

# Custom vars
githubrepo:          'https://github.com/duraspace/pcdm'
wiki:                'https://github.com/duraspace/pcdm/wiki'
emaillist:           'https://groups.google.com/d/forum/pcdm'
ircdiscussion:       '#pcdm on irc.freenode.net'
